version: '3.8'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootp
      - DB_NAME=auth
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootp
      MYSQL_DATABASE: auth
    ports:
      - '3307:3306'