name: auth-app

services:
  backend:
    build: .
    container_name: auth-app-backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ./wait-for-it.sh db:3306 -- npm run dev
    restart: unless-stopped

  # frontend:
  #   build: 
  #     context: ../fe
  #     dockerfile: Dockerfile
  #   container_name: auth-app-frontend
  #   ports:
  #     - "3001:3001"
  #   volumes:
  #     - ../fe:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://localhost:3000
  #     - NODE_ENV=development
  #     - PORT=3001
  #   depends_on:
  #     backend:
  #       condition: service_started
  #   command: npm run dev
  #   restart: unless-stopped

  db:
    image: mysql:8
    container_name: auth-app-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}`
      MYSQL_DATABASE: ${DB_NAME}
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
    name: auth-app-mysql-data